### PR TITLE
propagate exporter logger to WSGIServer

### PR DESCRIPTION
**Pull request by ahuret**
Adding verbosity control on exporter server side.

### CODE REVIEW

**Comment by elukey** [comment]
Hi @ahuret, thanks a lot for the patch. Can you add a bit more details about what is your use case and why this change is needed? More than happy to merge but I'd like to understand it a bit more.

We use github as mirror for https://gerrit.wikimedia.org/r/admin/repos/operations/software/druid_exporter, so there are two options:
1) I commit your changes adding credits to the commit msg.
2) You register to Gerrit, checkout the repo and create a code review (should be as simple as `git clone etc..` and `git push origin HEAD:refs/for/master`).

Let me know :)

**Comment by ahuret** [comment]
Hi @elukey :)

For now exporter allow to decide if logs are debug or warn, but only at exporter level, and since exporter use external services (as `WSGISERVER`) logs verbosity for these external services is not handle. This change allows to use the same logger and then use the same verbosity for the entire application (exporter + external services).

With this change, I can disable debug mode and then don't have 'INFO' WSGISERVER logs.

Next step would be to allow user to decide which verbosity he wants (debug/info/warn/error/fatal) (by adding a verbosity/log-level argument to cli). But imo better to keep it for another iteration since it requires much more work.


Gonna push directly to Gerrit. Thx :)

**Comment by ahuret** [comment]
https://gerrit.wikimedia.org/r/c/operations/software/druid_exporter/+/608607

**Comment by elukey** [comment]
Ahhh got it, for example the access logs from WSGI are not logged anymore if not using `--debug` (from what I can see from a quick test). It seems that adding the custom verbosity shouldn't be very hard, would you be interested in attempting a patch? Always nice when people from the community send patches, otherwise I'll try to work on it :)

**Comment by ahuret** [comment]
Yep it shouldn't be much complicated : 

- Adding log-level argument to cli
- Parse log-level (ensure it's valid)
- Add a switch case to set level to `logging` library

I don't have time for contribution now but I'll be happy to review :)

**Comment by ahuret** [comment]
closing it while it was merged on gerrit: commit 93eaecda5d27f9f105ab8b78eb0ab77e4903cb1e

**Pull request closed without merging**
